### ISSUE TITLE
Error on artist page

### ISSUE THREAD

**Issue by A2va** [KRTirtho/spotube#1018]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For this [artist](https://open.spotify.com/artist/75eQ7NabzgaaUYcrqSY0FK) page it displays `type 'double' is not subtype 'int?' in type cast` instead of the albums and songs.

### Expected Behavior

Display the artist page correctly.

### Steps to reproduce

1. Open Spotube
2. Connect with Spotify acccount
3. Search Regal Lily
4. Go to the artist page

### Operating System

Windows 10.0.19045.0

### Spotube version

v3.4.0

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev), WinGet (Windows)

**Comment by asuka-405** [comment]
Not just regal lily, it happens every time u try to navigate to artist page through the music player.

**Comment by KRTirtho** [comment]
That is happening due to a recent change in the Spotify API. Sadly, it's on library level. It'll take sometime.

Keep tracking https://github.com/rinukkusu/spotify-dart/issues/193

**Comment by wi2david** [comment]
![Screenshot_2024-01-07-02-33-34-36.jpg](https://github.com/KRTirtho/spotube/assets/132403917/6eaf40f8-7015-4adb-a149-212f806b0915)

This 👆🏽

**Comment by hayribakici** [comment]
I tried to build this project on my machine (macOS 14.1.2), however somehow it does not build. Anyways, is there any way to take a look at that received `artist` json from the API, so that it could be examined more closely?

**Comment by hayribakici** [comment]
This looks like a spotify API issue ([1](https://community.spotify.com/t5/Spotify-for-Developers/The-response-type-of-artist-endpoint-is-marked-as-Integer-in/m-p/5800044#M12164), [2](https://community.spotify.com/t5/Spotify-for-Developers/Get-Artist-reference-bug-receiving-Float-instead-of-Int/m-p/5800321)).

**Comment by taha-ghadirian** [comment]
Hello dear maintainer @KRTirtho. As there are many duplicate issues about this problem, I kindly suggest to pin this issue and close duplicate issues. 
So users can refer to this issue as main thread and track the problem all in one place.

**Comment by KRTirtho** [comment]
Agreed

**Comment by KRTirtho** [comment]
I've implemented a custom endpoint which eradicates this issue. It'll be available in the nightly shortly

**Comment by Zane2b2t** [comment]
im also getting this. wanted to search if someone else did instead of making a duplicate

**Comment by terrarier2111** [comment]
> I've implemented a custom endpoint which eradicates this issue. It'll be available in the nightly shortly

Will there be a new release including this fix in the near-future?

**Comment by BlorisL** [comment]
I've faced the same issue on the Android version.
I will wait for the fix in the store 🙂

**Comment by GrampaWildWilly** [comment]
I'm on Windows 11 Pro 64-bit version 23H2 build 22631.3085.  I decided, based on your comment above about having fixed something to do with an endpoint, to try a nightly.  I have no idea what you're talking about but I'm allowed to be a dumb user sometimes, right?  So I went here https://github.com/KRTirtho/spotube/releases/tag/nightly & got  Spotube-windows-x86_64-setup.exe.  Before executing that, I uninstalled Spotube.  Then I ran that installer.  I let the installer go ahead & launch Spotube in the last step.  Now, I can't even open Spotube.  I think whatever you did is making something wait for the problematic artist display earlier & it's blocking the app from launching properly.  I've rebooted & nothing changes.

One kind of curious thing I've noticed.  When I look in the All apps list, there's 2 instances of Spotube.  When I do the open file location trick, I find 2 almost identical shortcuts to Spotube in 2 different directories in the Windows directory structures.  I'm wondering why you've done that.  Wouldn't just one shortcut be enough?  The uninstall leaves one of them behind.

I said almost identical.  The shortcut in <user>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs shows a Start in value of <directory structure>\spotube.exe.  Windows complains about this when I go to close the Properties dialog on the shortcut.  The other shortcut correctly shows simply <directory structure> in the Start in box.  This seems like a minor issue so I doubt it's causing the problem under discussion in this thread.  Still, it's not right.  I say either fix it or don't create it.  The other shortcut seems to be correct.  Wouldn't having just that one by itself be good enough?

**Comment by GrampaWildWilly** [comment]
I looked for a new nightly & found one that is only about 6 hours old.  Spotube's own About says this is V3.4.0 nightly 196.  Revo Uninstaller reports it as 3.4.0+27196.  It actually plays stuff, so I thank you for the work you are so obviously continuing to put into this.  But there are some rather lengthy delays at certain moments.  They have even made me close it because I thought it had crashed.  It appears all it takes is a bit more patience on my part.

I am going to speculate on why it's delaying.  When I click Shuffle, it looks like it populates the queue with the tracks in the appropriately shuffled order.  Problem is it creates the queue using EVERY track in my playlist, which number is 7,657 to be precise.  I would suggest that if you want to make an internal list in some area of program storage with all 7,000+ entries, that's fine.  But build the thing that you can display by clicking the Queue button to include only the next, let's say, 20 tracks from the top of the queue.  That should eliminate a lengthy delay.  You can incrementally update the Queue display as each track plays.  Remove from the top the track that just completed, roll the next track up to the top, & insert the next track from the in-storage list into slot 20 at the bottom of the Queue.  Make the thing that displays the Queue show only the next 20 tracks that will be played.  That should be enough.

I really should look at the Wiki to see if I can learn how to use this thing properly without just guessing & clicking here & there hoping to discover some new knowledge.  But for now, I've managed to make it play.  I am most grateful for this program.  I have been unable to access my Spotify playlist for about a year so I'm quite pleased to be getting it back.

I'm not sure the Artists button works yet.  I've just clicked it & all it shows is the spinning graphic.  But this might just be another of those long processes that I should just be patient with.  So I'm going to leave it spinning for at least a half hour.  I will try the Albums button later, after I give up on the Artists button.  Or after the Artists button finally shows some results.  I should be more optimistic.

**Comment by GrampaWildWilly** [comment]
For the past more than an hour I've been listening to my shuffled playlist just fine.  But the Artists thing is still sitting here spinning.  It's not displaying anything.  What is it supposed to show me, anyway?  Is it supposed to be a list, in either icon or details form, of every artist whose content I have in my playlist?  Or is it supposed to be every artist represented on Spotify?  Either way, it's not displaying anything.  I'm leaving the Albums button for another time.  And once again, what is it supposed to show me?  The albums in my playlist or a list of every album on Spotify?

**Comment by GrampaWildWilly** [comment]
Do I really need to uninstall the previous Spotube before I install a new one?  I will presumably be sticking with nightlys from now on, although I will probably not be assiduous about getting every single one as it is released.

Because I did uninstall the previous Spotube, this one made me reconnect to Spotify, which means fishing that skanky character string out of the Firefox devtools.  Note the singular.  The first time I did this with a previous installation, I had to fish 2 strings out of devtools.  This time, I had to get only 1.  Is that something new coming to the regular releases of Spotube?  I understand why I had to reconnect, although when I got onto Spotify to do the devtools thing, I was still logged on.  I intend to never log off of Spotify from this point forward.  I also will not log off of Spotube.  That should simplify things.

I am pleased to note that after closing & relaunching Spotube, the shuffled queue is not created over again.  It picks up with the last track I was listening to on the preceding run & continues to sweep through the shuffled queue that was already in progress.  Back when Spotify was still working for me, closing & reopening the app created a new shuffle.  I think it's 6 of one, half a dozen of the other on this score.  But I'm happy with how Spotube does it because the creation of the shuffled queue locks up Spotube for rather a long time, during which you just need to be patient & not mistake the state of things for a crash.  Perhaps you could reassure users by putting up some kind of spinning thing with a comment that this can take rather a long time & you should just sit tight & wait.

I should try the Albums button now.  I'll report on that in an hour, maybe longer.

**Comment by GrampaWildWilly** [comment]
That was quick.  The Albums button just shows an open box with the comment that there's nothing to show.  I really need to go read up on these things.

**Comment by GrampaWildWilly** [comment]
Well that was disappointing.  The Wiki is empty.  Isn't there any documentation anywhere for this?  Or are we meant to just stumble around & discover everything by experimenting, trial & error, guessing?

**Comment by muzhawir** [comment]
![Screenshot_20240125_210201_Spotube.jpg](https://github.com/KRTirtho/spotube/assets/7391703/f2b84edd-9e23-49c5-be12-e7bfdadf1771)

I also get the same issue, when tapping on an artist's name.

Version: 3.4.0
Build number: 27

**Comment by GrampaWildWilly** [comment]
The more I use this, the more I don't like the way the queue is managed.  I have 7,657 tracks in my playlist.  When I clicked the shuffle button, Spotube put all 7,657 tracks into the queue.  That took several minutes, to the point that I thought the app had crashed.  I know that in principle, when you click shuffle, your entire playlist goes into the queue.  In principle.  Conceptually.  But you don't need to show all 7,657 tracks in the display of the queue.  It takes an inordinate delay while you build that.  At least you don't rebuild it each time I launch Spotube.  But I don't think anybody needs to see a queue that is nothing more than a shuffled version of their full playlist.  Just show 20 tracks, starting with the one that is playing now.  Not every track that has already been played, which is what you do now.  When I first launch Spotube & open the queue, it starts at track #1 & quickly scrolls down to the track I'm playing now.  I haven't had Spotube for very long so I'm only about 100 tracks in.  So the scrolling is quick.  But when I get a significant distance into this queue, I'm going to have to sit & wait while it scrolls 1,000, 2,000, 3,000, and more lines.  This is just silly.  Show the next 20 & stop there.  Don't even permit scrolling into the future past those next 20.  You might want to keep the full shuffled list of 7,657 tracks somewhere in program storage or maybe even in a file.  But there is no need to show all 7,657 of them in the queue within the app.  And don't show ANY track in the queue that has already been played.  Don't show it in the queue.  Separate that out to another display, a history queue if you will.  Display that starting at the bottom, meaning the most recently played track.  And display only the 20 most recently played tracks.  I suppose here, you can allow the user to scroll up beyond the 20 most recent tracks, but do it in increments of 20 just to keep the display responsive.  But don't show any history in the queue.  History should be a separate display.

I was scrolling through my playlist, not the queue now, the playlist.  I expected it to show all 7,657 tracks that it put in the queue.  But that's not what happened.  It got to track number 5,919 & stopped.  If I hadn't already done the shuffle thing & seen that the queue contains all 7,657 tracks, I would have been very upset that I was missing 1,738 tracks from my playlist.  So there's something wrong with the playlist display cutting off before the last track.

Something else is wrong with the playlist display as well.  I told it to sort by artist.  I don't know what order you are using but it isn't in alphabetical order by  artist.  Moreover, as I scrolled through it I saw albums from the Beatles, The Rolling Stones, BB King, Shakira, Robert Cray, Mana, not in alphabetical order, and then some more of the Beatles, then some others, & even later some more of the Beatles.  Not all of the tracks from a given artist are shown in a single block.  They're scattered about throughout the list.  Plus it is simply not in alphabetical order.  AC/DC should be pretty much at the top of my playlist if it's sorted in alphabetical order.  Instead, the first artist listed is Creedence Clearwater Revival.  AC/DC is a couple of thousand places down in the list.

Now, in addition to sorting properly on the artist's name, you should display each of that artist's albums with the tracks in order.  I know this information is available to you because I downloaded one track as an experiment & the track number was in the file's properties.  So you can sort the tracks by track number within album.  Further, another thing I saw in the file properties of that downloaded track was the year of the album's release.  So within each artist's content you should sort the albums by release date, & within each album, sort the tracks by track number.  Sorting can be done on multiple sort keys.  You should do it.  Of the sort keys I'm suggesting, only the artist's name should be an alphabetical sort.  The others are numerical sorts.  It would be nice if you could sort Robert Cray using C, BB King using K, etc.  In other words, sort using last names, when possible.  The Rolling Stones would have to be sorted using R.  Note, not T for The.  R for Rolling.  In other words, use international standard conventions for sorting.

On the days when I added things to my playlist, all of the tracks I added could be played on Spotify.  But I have discovered over time that certain tracks have become unplayable.  I'm guessing this has been due to some stupid lawyer intervention, something to do with copyrights.  I guess Spotube can't play something that Spotify refuses to supply.  But I've discovered that when you hit one of these tracks, Spotube just stops.  I have to manually kick it forward to the next track to make it resume playing.  You should just skip the track.  Maybe flag the entry in the queue with some indicator that the track is no longer accessible.  But that would be optional.  Just don't quit playing.  Move on to the next track.

Different tracks are recorded at different levels.  I get that.  Most of my queue plays at a reasonable volume level.  But here & there I've hit a track that is almost inaudible.  I understand this is not a Spotube problem, but just the way the item was engineered.  I have found a Spotube setting called Normalize audio.  What does that do?  In the absence of documentation, I guessed that it would boost these quiet tracks.  Possibly even tone down louder tracks.  But the setting seems to do nothing.  What's it for?  Do you have something that will do what I'm describing here?  That is, boost severely quiet tracks & ease down severely loud tracks.

I have been looking for a way to select multiple tracks.  For example, I should be able to highlight & select all the tracks of an album.  I'm thinking about the download function.  If I want to download my playlist, it looks like I could do it only one track at a time.  There's no way I'm clicking 7,657 times to download each track.  Since the Wiki for Spotube is empty, I can't look up how to select multiple tracks.  The usual thing would be clicking one entry, then holding down Shift & clicking another track further down.  Or up.  Or position on one track, hold down Shift, then type PageDown until you've selected everything you want.  Also, the Home key should go to the top of whatever you're looking at & the End key should go to the bottom.  These are just standard GUI behaviors in standard Windows apps.  I don't even see that any of your displays has a current line marked with a selection.  Look at any other app.  There is a highlight on the current object, & using the UpArrow, DownArrow, PageUp, & PageDown keys moves that highlight.  You can also type a letter & the list will jump to the next entry that begins with that letter, moving the current line highlight at the same time.  I'm not asking for much here.  It is standard behavior.  Spotube does not conform to standard GUI design.  You should fix this.  Just because the original Spotify app doesn't conform to standard GUI behavior doesn't mean you have to do what they do.  I thought you were trying to be better than they are.

As far as I know, my playlist is publicly accessible.  It's under my ID, GrampaWildWilly.  I encourage you to use it for creating & testing the fixes I'm proposing here.

**Comment by GrampaWildWilly** [comment]
I've noticed that the entries in my playlist for Little Feat are attributed to a group call Little.  Ummm....... no.

I just had a rather odd occurrence.  On a track by Roy Buchanan called Messiah from the album titled Live at Rockpalast, the track duration is listed as 7:18.  But once it started playing, the player showed it would last 1:16:40.  In other words, a simple short track actually had a full album hiding within it.  I'm not sure where the problem lies with that.  It might just be whatever Spotify is feeding you.  You can check this out yourself.  My playlist is available for you to look at.

**Comment by shishkin** [comment]
@GrampaWildWilly would you mind giving your feedback unrelated to the error on artist page through separate issues? This issue is resolved as [mentioned before](https://github.com/KRTirtho/spotube/issues/1018#issuecomment-1903965682). The only relevant discussion here is when will be the next stable release.

**Comment by KRTirtho** [comment]
@GrampaWildWilly I don't wanna be rude but please don't just dump huge paragraphs. Instead structure your problems properly because nobody tbh has time to read this much text. Also, this is thread is for a specific issue. Please do not generilze it for all sorts of problems you're facing. So I'm marking some of your unrelated comments as off-topic. 

If you're not a pro/technical user, you can ask for help/guidance in the Discord server. There are many who will guide you through your problems. GitHub issues are meant for technical reports and observation of errors or for submitting new ideas structurally

**Comment by KRTirtho** [comment]
I'm also locking this thread as this particular issue has been resolved and available in the Nightly.

Also, you don't have to uninstall the old version of spotube before upgrading. If nothing changed, Spotube installer will automatically point to the directory it was installed before and replace the old version with new one. But make old Spotube isn't running in the background
