### ISSUE TITLE
Blank screen at start  

### ISSUE THREAD

**Issue by ThierryParis** [KRTirtho/spotube#1063]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

At restart of windows 11, spotube appear as a blank screen.
Some buttton are working (is it possible to launch music)
I tried to install again spotube, but same issue.

### Expected Behavior

Spotube windows should be ok

Nevertheless , there is a solution:  Resize the spotube windows  makes the images reappear

### Steps to reproduce

Open windows 11
Open spotube

### Operating System

windows 11

### Spotube version

3.4.0

### Installation source

GitHub Releases (Binary)

**Comment by user10246** [comment]
uwp maybe




David
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KRTirtho/spotube"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月14日(星期天) 下午4:29
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[KRTirtho/spotube] Blank screen at start   (Issue #1063)





 
Is there an existing issue for this?
  
 I have searched the existing issues
  
Current Behavior
 
At restart of windows 11, spotube appear as a blank screen.
 Some buttton are working (is it possible to launch music)
 I tried to install again spotube, but same issue.
 
Expected Behavior
 
Spotube windows should be ok
 
Nevertheless , there is a solution:  Resize the spotube windows  makes the images reappear
 
Steps to reproduce
 
Open windows 11
 Open spotube
 
Operating System
 
windows 11
 
Spotube version
 
3.4.0
 
Installation source
 
GitHub Releases (Binary)
 
Additional information
 
No response

**Comment by localuser-isback** [comment]
I have this same issue.

**Comment by BSLprints** [comment]
I just installed this app for the first time ever and had the same issue (windows 11, current release version of spotube). 
Uninstalling and installing the most recent (as of 2024-02-08) nightly build fixed it for me.

**Comment by aldocaniza** [comment]
I resolved this issue by uninstalling Spotube with Revo Uninstaller, then reinstalling it in Users/AppData/Local.
