### ISSUE TITLE
Discord RPC not working

### ISSUE THREAD

**Issue by JaredFeeney** [KRTirtho/spotube#1140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using the Discord Flatpak, Rich Presence isn't functioning with the Spotube Flatpak or AUR package. I have verified the option for DRP is enabled in the settings. RP does work when using the Spotify web player in a browser

### Expected Behavior

Discord rich presence should be synced with Spotube information but isn't

### Steps to reproduce

Start any song or playlist

### Operating System

Arch Linux

### Spotube version

3.4.0-2

### Installation source

Arch User Repository (AUR)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by Peperehobbit01** [comment]
I dosen't work for me either on linux mint whit the flatpak version of Spotube xD and the Discord.deb version. By the way @Enigma1309 it's never gonna work for you because your not using the offical app of Discord and your just using a Discord web as a app. So you have missing feature. I recommend you using the official version of Discord, as there is all the feature like the rich presence stuff.

**Comment by Peperehobbit01** [comment]
For wayland I have no idea if it's good and stable but it's pretty good tho, but for privacy I do not realy no webcord so... I don't no what privacy option we are talking about here.

**Comment by Peperehobbits01** [comment]
> yeah thanks for the point-out, i've realized it recently :)
> 
> anyways i'm not switching back to official app soon since webcord provide better privacy options and screen-sharing on Wayland.
> 
> i'll switch to the official app if they add those features and give a stable experience

And as far as I am aware it's stable now a days, but for privacy... I think you are going to wait for a long time... very long time and for the issues well this is issues is probably never going to be fixed for me because I use the flatpak version of Spotube, but for this arch user d'amm, that's kind of sad, tho @JaredFeeney know that I have realised but your issues dosen't makes sense the reason why spotify works on web and as the rich presence whit the Discord Flatpak but spotube whit the flatpak or the arch version dosen't work is because they don't use the same thing. The spotify rich presence is showing up regardless of the devices and the official app you use of Spotify, because of your spotify account being linked to your Discord account. On the other hand, Spotube uses the rich presence API of Discord to show from the app installed on your devices to the Discord client (aka app) installed on your PC when it's opened the info for the rich presence that he want's to show up on your profile but you are using the flatpak, that runs in a container, which is making some limitations like, making custom rich presence on your profile whit Spotube or other apps. I know that there is no arch version of Discord, so to have this bugs fixed your going to have to wait for Discord to fix it or for @KRTirtho to make the app look for the Discord flatpak if you use the Spotube arch build. Tho, if it is possible to verify that any Discord is installed on a flatpak that would be cool to, but it's not the same problem as here techniquely, it gives the same results tho.
