### ISSUE TITLE
Custom shortcuts don't work (Flatpak, Fedora 36 Workstation)

### ISSUE THREAD

**Issue by onlyreportingissues** [KRTirtho/spotube#116]
The app doesn't react to my custom shortcuts. It doesn't play the previous track, next track and it doesn't pause either. 

Ctrl + Num 4: previous track
Ctrl + Num 6: next track
Ctrl + Num 0: pause

**Comment by theCalcaholic** [comment]
FYI: The reason for this is most likely that Wayland doesn't allow global shortcuts (yet). Compare these issues from other applications:

- https://github.com/albertlauncher/albert/issues/309
- https://github.com/Guake/guake/issues/492
- https://github.com/clementine-player/Clementine/issues/5462

**Comment by KRTirtho** [comment]
Well, instead of global hotkey Spotube directly ships with OS Media Control Keys support. So you can now control music with your keyboard's Media Buttons in Linux

This has been fixed in the latest release v2.3.0. The Flatpak edition usually becomes available after a certain delay

**Close this issue if your requested feature/bug is implemented/fixed + released**

**Comment by dejalavidavolar** [comment]
Hi, I hope you are well. I'm having the same problem on Linux Mint 21 Cinnamon. The multimedia keys (f9, f10 and f11) don't work for me, neither do the audio controls in the taskbar. With other applications (e.g. spotify) it works for me, but with Spotube I have not been successful.

Regards!
