### ISSUE TITLE
MSVCP140.dll & VCRUNTIME140.dll not found error

### ISSUE THREAD

**Issue by mad4some** [KRTirtho/spotube#12]
After installing the windows version on my HP Pavillion/2021 model/Windows 10 and trying to run, all I get is pop up errors of "MSVCP140.dll not found" followed by "VCRUNTIME140.dll not found". Uninstalled and re-installed a few times with no success and same behavior each time.

**Comment by KRTirtho** [comment]
These are common errors for Windows applications & they occur because of missing some essential runtime component in Windows. These errors are completely unrelated to this project but still here's a fix

Install [Microsoft Visual C++ 2015 Redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=53840) to fix "MSVCP140.dll not found" & "VCRUNTIME140.dll not found"

**Comment by KRTirtho** [comment]
Closing this issue as it isn't related to this project & the issue creator hasn't responded

**Comment by mad4some** [comment]
Thank you!...and sorry I had not responded as I've been rather busy and
this is not my main email, yeah I know...poor excuses!! Thanks again 😀

**Comment by KRTirtho** [comment]
No prob. I knew it's a definite fix for this kind of common windows problem thus I was confident enough to close the issue
