### ISSUE TITLE
Spotify Connect

### ISSUE THREAD

**Issue by Cosmic-Wolf** [KRTirtho/spotube#1344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Hi, so I love the Spotube App and I have been using it for quite a while now. I love the app, but the only thing that kept me from completely ditching Spotify was Spotify Connect. Basically, I could be playing music on my ;aptop, but I can control playback from my phone, as if it were a remote, and that is so useful.

### Suggested solution

 I was wondering, if it was possible to somehow integrate Spotify Connect into Spotube?

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by Peperehobbit01** [comment]
That's a feature i almost forgot about x) , but if I would be honnest it's not impossible and it's defenetly a great feature that should exists but it will clearly not be based of the Spotify Connect feature because if I remember correctly this thing is not availeble on the spotify website but I am not sure 100%. Honestly if I was enough talented as a developer I would of submited a PR for this but... I am not right now x) .

**Comment by 123Sanyam123** [comment]
+1. This is a must have honestly

**Comment by AITleo** [comment]
https://github.com/KRTirtho/spotube/pull/1355 has been merged and released in [v3.6.0](https://github.com/KRTirtho/spotube/releases/tag/v3.6.0).

It does not incorporate spotify connect but it's own mDNS based discovery.

I think this can be closed.

**Comment by PeteS4** [comment]
While definitely useful, the new feature is not really Spotify Connect, is it? Neither does it allow to control embedded Spotify Connect capable devices such as A/V receivers or KODI's Spotify plugin, nor can the playback in Spotube be controlled from an official Spotify client.

**Comment by Peperehobbit01** [comment]
You are kind of asking for the imposible at this point bro
