### ISSUE TITLE
[Windows] Distorted window on startup

### ISSUE THREAD

**Issue by KRTirtho** [KRTirtho/spotube#1553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After launching the exe, the Window of the app is distorted and zoomed, overall unusable.

![image](https://github.com/KRTirtho/spotube/assets/61944859/f2e3fd8b-10a9-4c88-8a20-ac9034e2f699)

### Expected Behavior

Usable window

### Steps to reproduce

1. Install the app on Windows 10/11
2. Open the app

### Operating System

Windows 10, Windows 11

### Spotube version

v3.7.0

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev), GitHub Releases (Binary)

### Additional information

**Workarounds**:
1. Simply resizing the window each time after launching completely fixes the issue
2. To permanently fix it, turn on "Settings" > "Desktop" > "Use system titlebar"

### Self grab

- [X] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
### Workarounds to fix the issue:

- **Temporary Fix:** Simply resizing the window each time after launching completely fixes the issue
- **Permanent Fix:** Turn on "Settings" > "Desktop" > "Use system titlebar"

**Comment by DerekGooding** [comment]
Note on the workaround. 

System titlebar is currently bugged. Cannot see minimize or fullscreen buttons although they are clickable where you'd think they would be.

**Comment by Speedylux** [comment]
Additionally the following problems occur in parallel:

a) drag and move window around does not work any longer with v3.7.0
b) resizing and making window much smaller in non-maximized view does not really work any longer in v3.7.0

**Comment by UTFX0150** [comment]
![image](https://github.com/KRTirtho/spotube/assets/123019149/55fc1f1f-2bda-4138-b4c6-d1e6bbdd0fb3)
uhhhhh

**Comment by Fe1777** [comment]
Certainly! Below is a structured GitHub issue description related to the distorted window issue on startup for the Spotube application on Windows:

---

**Title:** [Windows] Distorted Window on Startup

**Issue Description:**
After launching the executable (exe) of the Spotube app, the window appears distorted and zoomed, rendering it overall unusable.

**Is there an existing issue for this?**
- [x] I have searched the existing issues.

**Current Behavior:**
On startup, the application window appears distorted and zoomed. The content is not appropriately scaled, making the application unusable. 

Example Screenshot of the Issue:
*(Here the user should ideally attach a screenshot if available.)*
```
[Spotube Distorted Window Screenshot]
```

**Expected Behavior:**
The application window should initialize properly without any distortion or zooming, displaying the content as designed and making it fully usable.

**Steps to Reproduce:**
1. Install the application on Windows 10 or Windows 11.
2. Open the application.
3. Observe the distorted window behavior on startup.

**Operating System:**
- Windows 10
- Windows 11

**Spotube Version:**
- V3.7.0

**Installation Source:**
- Website: [spotube.netlify.app](https://spotube.netlify.app)
- [spotube.krtirtho.dev](https://spotube.krtirtho.dev)
- GitHub Releases (Binary)

**Additional Information:**

**Workarounds:**
1. Resizing the window after each launch fixes the issue temporarily.
2. To permanently fix the issue, enable the setting: "Settings" > "Desktop" > "Use system title bar".

Example Screenshot of the Workaround:
*(Here the user should ideally attach a screenshot if available.)*
```
[Spotube Window with Use System Title Bar Enabled]
```

**Self-Assignment:**
- [x] I'm ready to work on this issue!

Any additional comments or notes regarding the issue? Feel free to add them here.

---

**Thank you, and let's work towards resolving this issue to improve the user experience on Windows.**

End of Issue description

This Issue description includes:

1. **Title**: Clearly states the problem related to the Windows platform.
2. **Issue Description**: Provides an overview of what happens when the app is launched and what the user experiences.
3. **Existing Issues Search**: Confirms the user has searched existing issues.
4. **Current Behavior**: Describes the problem in detail, including how the window is distorted.
5. **Expected Behavior**: Clearly states what should happen upon launching the application.
6. **Steps to Reproduce**: Makes it easy for others to replicate the issue.
7. **Operating System**: Identifies the operating systems where the issue occurs.
8. **Spotube Version**: Specifies the version of the application.
9. **Installation Source**: Lists where the app was installed from.
10. **Additional Information**: Provides known workarounds and steps for a temporary and permanent fix.
11. **Self-Assignment**: Indicates the user is ready to work on the issue.

Feel free to modify this template to suit any additional requirements or preferences!

**Comment by skruglov2023** [comment]
![image](https://github.com/KRTirtho/spotube/assets/55259393/8199c8a6-0f15-4b95-975d-8a27cbaf5bcf)
the windows tray icon is also distorted. 
I can also confirm that the drag and move options are no longer working. I can move the app either by resizing, or by using win+arrows to move/snap it to windows preset locations.

**Comment by KRTirtho** [comment]
Version 3.7.1 has been released with the fix
