### ISSUE TITLE
Windows 64 Bit download link download v3.7.0 instead of v3.7.1

### ISSUE THREAD

**Issue by tkoeck** [KRTirtho/spotube#1643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Windows 64 Bit [download link](https://github.com/KRTirtho/spotube/releases/download/v3.7.1/Spotube-windows-x86_64-setup.exe) downloads v3.7.0 instead of v3.7.1

### Expected Behavior

It should give me version v3.7.1

### Steps to reproduce

1. Download https://github.com/KRTirtho/spotube/releases/download/v3.7.1/Spotube-windows-x86_64-setup.exe
2. Install it

### Operating System

Windows 10

### Spotube version

3.7.1

### Installation source

GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by Peperehobbits01** [comment]
You haven't search the existing issues sir, because if you had you would of found this https://github.com/KRTirtho/spotube/issues/1595 and this https://github.com/KRTirtho/spotube/issues/1648 . So please to make the work of developers easier, could you close this issues, this help to make the issues tab more clean and allow for faster reading, so bugs can be fixed more quickly, because they can be readed faster.

**Comment by tkoeck** [comment]
Yeah, you are right. I did search for it but didn't see it.
