### ISSUE TITLE
Randomly skips songs after about a minute

### ISSUE THREAD

**Issue by aj9669** [KRTirtho/spotube#1679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The app sometimes skips some songs after about a minute or 90 seconds (however, i have found no clear time pattern), without me pressing anything. It's also not a problem with my headphones (it happens with many of them) and I don't think it's a OS problem because it doesn't happen with any other app. The only thing I observe that it typically skips the first 2-3 songs after an app restart, and when I listen to music longer than that it doesn't occur anymore.

### Expected Behavior

It should play the whole song and only skip it when I want it to.

### Steps to reproduce

No idea, just randomly occurred one day (I think it was the one update, that made songs play first that are already loaded). 

### Operating System

Android

### Spotube version

newest

### Installation source

F-Droid (Android)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
This happens when there are no matches found for a particular song. But previously there wasn't enough results in the first place to switch to another source. But it was fixed in the #1687 PR

Try out the nightly channel it should be better than before. Although extremely less popular or really old songs might get skipped due to YouTube not having it
