### ISSUE TITLE
Can't log in with spotify 

### ISSUE THREAD

**Issue by Szprej0** [KRTirtho/spotube#1871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The spotube opens as expected but when I try to log into Spotify no matter what I do the button won't do anything. I've tried reinstalling the app but it didn't fix my issue.

### Expected Behavior

The Connect Spotify account should work

### Steps to reproduce

1. The app opened normally.
2. I opened the settings 
3. I clicked on a connect Spotify button
4. nothing happened

### Operating System

Windows 23H2

### Spotube version

v3.8.0

### Installation source

GitHub Releases (Binary)

### Errors from logs
[2024-09-11 20:07:05.431897]---
PlatformException(0, WebView runtime not available, null, null)
#0
#1
StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648) MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334)
<asynchronous suspension>
#2
WebviewWindow.create (package:desktop_webview_window/desktop_webview_window.dart:67) 
<asynchronous suspension>
#3
 SettingsAccountSection.build.onLogin (package:spotube/pages/settings/sections/accounts.dart:58) 
<asynchronous suspension>

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by TheBlackReverand** [comment]
In link with #1867 I think

**Comment by intox-ai** [comment]
any solution?

**Comment by Szprej0** [comment]
> any solution?

no updates from anyone

**Comment by KRTirtho** [comment]
The Login process requires [Microsoft Edge WebView2 Runtime](https://developer.microsoft.com/en-us/microsoft-edge/webview2/?form=MA13LH&ch=1) to be installed. You don't have that

**Comment by KRTirtho** [comment]
From the next version we'll show a warning about this so user won't be confused

**Comment by Szprej0** [comment]
after the 3.8.1 everything works just fine thx guys.

**Comment by marshel** [comment]
Hi, same here.


Spottube 3.8.3
Win11 24H2
Edge WebView2 is installed

My thoughts..
- Is it runnign firefox instead of edge?
- If yes, is it because the popup blocker blocks Spotfy and Facebook credential allow window?
- Is a bad request sent?
- Change in SF api?

Log:

#747    _drawFrame (dart:ui/hooks.dart:283)


----------------------------------------
---------
[2024-12-04 09:42:02.074305]---------------------
DioException [bad response]: This exception was thrown because the response has a status code of 401 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 401 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:509)
<asynchronous suspension>
#1      CustomSpotifyEndpoints.getFriendActivity (package:spotube/services/custom_spotify_endpoints/spotify_endpoints.dart:113)
<asynchronous suspension>
#2      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-12-04 09:42:02.295139]---------------------
Error Code: 401
Valid user authentication required
#0      SpotifyApiBase.handleResponseWithBody (package:spotify/src/spotify_base.dart:282)
#1      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:256)
<asynchronous suspension>
#2      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#3      Me.get (package:spotify/src/endpoints/me.dart:22)
<asynchronous suspension>
#4      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-12-04 09:42:02.302168]---------------------
Error Code: 404
Not Found
#0      SpotifyApiBase.handleResponseWithBody (package:spotify/src/spotify_base.dart:282)
#1      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:256)
<asynchronous suspension>
#2      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#3      Pages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:253)
<asynchronous suspension>
#4      FeaturedPlaylistsNotifier.fetch (package:spotube/provider/spotify/playlist/featured.dart:33)
<asynchronous suspension>
#5      FeaturedPlaylistsNotifier.build (package:spotube/provider/spotify/playlist/featured.dart:44)
<asynchronous suspension>
#6      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-12-04 09:42:02.317700]---------------------
Error Code: 401
Valid user authentication required
#0      SpotifyApiBase.handleResponseWithBody (package:spotify/src/spotify_base.dart:282)
#1      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:256)
<asynchronous suspension>
#2      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#3      CursorPages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:292)
<asynchronous suspension>
#4      SinglePages.stream.handlePageAndGetNext (package:spotify/src/endpoints/endpoint_paging.dart:187)
<asynchronous suspension>

----------------------------------------
