### ISSUE TITLE
[Feature] Podcasts

### ISSUE THREAD

**Issue by SenorFusion** [KRTirtho/spotube#198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of the Feature

Logical Improvements

### Credits

Me

### Pain

Cannot play Spotify Podcasts through the app

### Suggested Solution

I did see the Readme that podcasts do not work. 

The reason given is that it would require premium, but Podcasts don't require Premium to listen to, so I am wondering why they can't be added to the UI?

I also searched the repo for any discussion of Podcasts and didn't find anything.

Does the API not allow access to podcasts?

Thanks for considering!

### Useful resources/references

Source: https://www.spotify.com/us/free/

**Comment by RaptaG** [comment]
Podcasts are not supported and possibly will never be because:

- There's no provider which could by any means be accurate enough to use it
- They are free _on the official app_. That's the reason Spotube uses YouTube for the songs. Spotify allows to use the official audios from Spotify only with a premium account. Spotube aims to be free forever for everyone. If there's a way to filter the podcasts to find them and also find a reliable provider, then this issue can be reconsidered

**Comment by mirh** [comment]
I'm not understanding why "totally free app without podcasts" is supposed to be a better alternative than "totally free app, plus optionally premium podcasts" (or "totally free app, and I still have to put up with that CEF behemoth for podcasts"). 

If you don't personally care (or you aren't a paid user and you still don't want to invest even a single penny) I could see why any work would feel like a waste of time, but it just seems so weird to make this instead a principled argument.

**Comment by DoktorBeSt** [comment]
I've seen that most bigger podcast also upload their podcasts to youtube, is it not possible to just take them from there?
