### ISSUE TITLE
[Feature] invidious/piped as backend

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [KRTirtho/spotube#293]
Wouldn't it be nice if I can choose to play songs via invidious/piped?

I use spotube to escape from spotify and stop it from eating my data but now I have to face yt (google) with my data so it would be nice to use invidious or piped instead! so I can save my data from spotify and yt

**Comment by IntoTheVoid-900** [comment]
This is not a good option, as it would require choosing an instance. That means that if the instance is far away, music will have a lot more buffering. Also, if the instance went down, then Spotube will stop working. Most Invidious/Piped instances experience regular downtime. It will generally result in worse UX.

If you are concerned about privacy, you should use a VPN.

**Comment by EsmailELBoBDev2** [comment]
You can add a drop menu for either of invidious or piped. So if the instance is down, the user can select something else.

**Comment by KRTirtho** [comment]
First of all, **Spotube doesn't send any kind of data to YouTube at all**
So don't be worried about privacy, as YouTube won't even be able to log any info about your device. YouTube can only save the public IP address (which changes quite often by the ISP) and nothing at all because Google can't run their ad libraries (Ad JavaScript Files) like they can in YouTube website to track your device for advertisement reasons

Secondly, indevious and piped both aren't reliable. I can add certain amount of instances in instance list but there's big chance all of them can die (at once except the official one) as mentioned by @IntoTheVoid-900 

Finally, time. It's already a huge overhead for Spotube to go and search on YouTube for the Spotube track and algorithmically rank and match the appropriate one. So IMO, there's no space for any extra latency

**Comment by EsmailELBoBDev2** [comment]
You had me at 

> First of all, Spotube doesn't send any kind of data to YouTube at all
So don't be worried about privacy, as YouTube won't even be able to log any info about your device. YouTube can only save the public IP address (which changes quite often by the ISP) and nothing at all because Google can't run their ad libraries (Ad JavaScript Files) like they can in YouTube website to track your device for advertisement reasons

Thanks for the details!
