### ISSUE TITLE
[Bug] [REGRESSION] only blurred screen

### ISSUE THREAD

**Issue by ildar** [KRTirtho/spotube#415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

navigating in the app made the app screen blurred (or shadowed, I don't know, check the screenshot).

Force stopping and Restarting doesn't help, only app data wipe.

### Expected Behavior

expect it working normally

### Steps To Reproduce

1. in a Playlist tap the artist.

### Spotube Version

nightly, installed Feb. 13

### Operating System

Android

### Operating System Version

Android 13

### Installation Source

Github Actions (Nightly Binary)

### Additional information

![Screenshot_20230215-151036_Spotube](https://user-images.githubusercontent.com/517752/218984936-29e41010-7e92-41db-a4cf-b934986469c5.png)

**Comment by ildar** [comment]
[logcat](https://github.com/KRTirtho/spotube/files/10741360/1.txt)

**Comment by KRTirtho** [comment]
@ildar  Let me know if latest version (v2.7.0) has fixed it

**Comment by KemonoElite** [comment]
![Screenshot_20230324_220518](https://user-images.githubusercontent.com/97435466/227688010-c743b3f1-08a2-4353-a3dd-83ec80126e27.jpg)

![Screenshot_20230324_220709_Settings](https://user-images.githubusercontent.com/97435466/227688042-503d5642-d677-4866-91fd-cb43f938252d.jpg)

It would seem this issue is still ongoing. I have had this happen to me on another android device. The app is up to date

**Comment by ildar** [comment]
Yes, just seen it on the 2.7.0

**Comment by gd0666** [comment]
@KRTirtho 

++BUG IS STILL ALIVE AND GOT WORSE - DER KÄFER KRABBELT NOCH++

Current Behavior

navigating in the app made the app screen blurred. 
Force stopping and Restarting doesn't help. 
Additionally no response of any kind whilst trying to navigate the app. The "blurr" seems to float like a popup, keeping me from interacting with the user interface. 

Expected Behavior

Be the grandiose app that it usually is (props to the dev! ) 

Steps To Reproduce

Like the OP I was switching between a song I was looking for and tapping on the artist that I assumed to be the creator, leading to the blur

Spotube Version

2.7.1 via F-Droid

Operating System

Android 11 RP1A.200720.011
MIUI Global 12.5.7 (stable) 


Installation Source

F-Droid

Additional information: Screenshot
![Screenshot_2023-05-10-08-51-53-373_oss krtirtho spotube](https://github.com/KRTirtho/spotube/assets/133090250/b22a6144-5fd4-4378-9be3-b65f0b867220)

**Comment by RaptaG** [comment]
Fixed in 3.0.0
