### ISSUE TITLE
Play related songs after playing a searched song

### ISSUE THREAD

**Issue by forteller** [KRTirtho/spotube#461]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Some times I want to hear a specific song right now, so I search for it. That does not mean that I only want to hear that song, though. Still when playing a song from search it is set to repeat for forever.

### Suggested solution

I prefer the way Spotify does it, where it automatically adds other, similar songs to the queue when playing a song from a search result. 

Thanks for a fantastic application I use every day! :)

**Comment by RaptaG** [comment]
This would require a bit of tracking tbh. Could possibly be done with local analytics

**Comment by KRTirtho** [comment]
This is the original task https://github.com/KRTirtho/spotube/issues/466

**Comment by lpstandardrp** [comment]
I have no idea if this idea is viable: what about implementing a a 'play/related tracks' function similar to those potentially found in or used by other apps (I dont know which, IIRC I found some really cool artists in Radio4000..). 

I was recently looking for this function of 'automatically adding similar tracks to the queue', and found some seemingly promising apps on AlternativeTo, again IIRC, a common tag/feature of most or all of the FLOSS apps was "Music Discovery Service." I seem to recall a notably *different* method of finding similar tracks (as opposed to Spotify's presumably tracking involved analytics) that involved something like pulling from users with similar interests from an open-source database, or...  using discogs similar tracks (or something along those lines... maybe libre.fm related, or..I'm  not sure) to find similar tracks by categories, users with similar interests, I am not exactly sure... I do remember thinking 'that sounds like a clever way to prevent user-tracking while at the same time capitalizing on the benefits of pulling from extensively analyzed open data sources *including* other users' 'radio channels' or 'favorites playlists')... in order to find statistically.probable matches for a users interest.. I hope that makes sense, if not or for a perhaps better explanation, the wording is probably more technically savvy, concise or succinct as found on the prospective apps' alternativeto.com page. 

*Note: each app has two pages/tabs: one for alternative apps (with filters for e.g. Android, Open-Source, etxc) on the '[App Name] Alternatives' page/tab,  and another containing said '[App Name]'s' Information, Reviews, Links, etc. A difference between the two is, in addition or as opposed to the '[App Name] Information, Reviews,...' page/tab, the '[App Name] Alternatives' page/tab has a place beneath each Alternative App where users can mention what is different between the two respective alternative apps, pros/cons, whether the respective alternative app is a good alternative and reasons why or why not...)

Regarding the apps I fohnd that may be of relevance, the notes I took for further investigation are as follows (*I hope it's okay to include this potentially long-ish list.. if not, my apologies* Also, some may beore relevant than others, someay be hardly if at all relevant; I am confident most are relevant from what I recall... it should be easy to tell pretty quickly with a quick skim through both tabs, User Reviews, and Users' Pros/Cons regarding an app as alternative to the other):

Music-(*LINKS*) re: Online Discovery Services, Streaming, Radio, Open Decentralized Musician Promotion and Monetization Platforms, Internet Radio Service

https://alternativeto.net/software/funkwhale/about/
https://funkwhale.audio/
https://radio4000.com/ (found on alternativeto.com)
https://alternativeto.net/software/blackhole-music-player/about/ (Also on Github; similar in functionality to Spotube,, maybe there is something or method they incorporate into their app that may be of use if only for ideas.)
https://alternativeto.net/software/audius-music/about/
https://alternativeto.net/software/radiodroid/about/
https://github.com/segler-alex/RadioDroid
https://alternativeto.net/software/openwhyd/about/
https://openwhyd.org/
https://alternativeto.net/software/navidrome/about/
https://alternativeto.net/software/tauon-music-box/about/
Tauon
https://tauonmusicbox.rocks/
http://subsonic.org/ (Probably not specifically relevant, I think this is local media server)

Tags (General, each app above may have one or more of these tags/features), separated by commas:
Music, Music Streaming Service, music discovery service, Open-Source, decentralized, communities, Internet Radio Service
Tags, one per line (separated by 'line breaks''— I think is what the new line separators are called) :
Music
Music Streaming Service
music discovery service
subsonic
music servers
Open-Source
decentralized
communities
Internet Radio Service

**Comment by BloodRaven0** [comment]
+1 This feature would be huge!
I know that [Nuclear](https://github.com/nukeop/nuclear) has this feature and it works really well. Maybe check what they're doing right and how?
Another way is to somehow hijack Spotify's suggestions, but I have no idea how much their free API allows.

**Comment by developer0395** [comment]
I came here search for `Start Radio` Feature. Yesterday I observed that its nothing but a playlist in spotify i.e. `${Song name} ${Radio}`. 

Thus a simple solution would be:
- User plays any song from search
- Starting playing that song
- In background search for the radio playlist by spotify
- Append those songs from the playlist

**Comment by KRTirtho** [comment]
This has been added in recent versions.

@developer0395 there's a separate issue for that.

**Comment by eaui1997** [comment]
Pain
After i play a chill song like: On the top (Chillpeach), it play other rock, pop,... song, not play related songs

Suggested solution 
I think we should find other sources to start a radio from a song playing like YouTube music, ...
Thanks for a fantastic application ♥️

**Comment by eaui1997** [comment]
Dear @KRTirtho 

Pain
After i play a chill song like: On the top (Chillpeach), it play other rock, pop,... song, not play related songs

Suggested solution
I think we should find other sources to start a radio from a song playing like YouTube music, ...
Thanks for a fantastic application ♥️
