### ISSUE TITLE
32-bit support (linux)

### ISSUE THREAD

**Issue by codenius** [KRTirtho/spotube#517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

app not available for linux 32-bit, might be useful for other users wanting to use an old laptop as a jukebox

### Suggested solution

include linux 32-bit packages in releases or provide compile instructions

**Comment by Peperehobbits01** [comment]
Yeah hum, since more and more apps drop the 32 bits support, I think that supporting it is just... well... 64 bits arived at least in 1994 so... and computers, from like 2008 already just used 64 bits, so I think it's asking for something pretty much useless, because those computers struglle to run modern Linux in the first place anyway.

**Comment by KRTirtho** [comment]
We don't plan add 32bit for OS. This is just too much to look out for. Just like Peperehobbits01 told in 2024 the 32 bit users is too low to support this architecture.
I'd advice to upgrade to x64 from x86
