### ISSUE TITLE
 Unhandled Exception: MissingPlatformDirectoryException

### ISSUE THREAD

**Issue by d2718nis** [KRTirtho/spotube#523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The application does not install `xdg-user-dirs` as a dependency if installed via Arch Linux AUR. Without this dependency it won't start and will throw an exception.
https://aur.archlinux.org/packages/spotube-bin

### Expected Behavior

PKGBUILD should have `xdg-user-dirs` as a dependency.
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=spotube-bin

### Steps to reproduce

1. Don't have an `xdg-user-dirs` package installed in the system
2. Install `spotube` from AUR
3. Run the app

### Operating System

Arch Linux

### Spotube version

v2.7.1

### Installation source

Arch User Repository (AUR)

### Additional information

Exception trace:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPlatformDirectoryException(Unable to get application documents directory)
#0      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:122)
<asynchronous suspension>
#1      HiveX.initFlutter (package:hive_flutter/src/hive_extensions.dart:12)
<asynchronous suspension>
#2      QueryClient.initialize (package:fl_query/src/core/client.dart:345)
<asynchronous suspension>
#3      main (package:spotube/main.dart:73)
<asynchronous suspension>
```

**Comment by GiorgosXou** [comment]
Thanks, I confirm that `pacman -S xdg-user-dirs` made it work

**Comment by KRTirtho** [comment]
xdg-user-dirs is a required [freedesktop specification.](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) That means all distros by default includes it. Spotube tries to follow the spec as much as possible. So it is expected to be installed on user's linux OS
In the case of custom built distros like Arch or Gentoo we can't help much as it is completely on user's hand to install it or not. Thus it's impossible for us to guess which specs are met in the base system or not on these distros. That's why `xdg-user-dirs` was decided to be not included as a dependency

**Comment by Avinash-Bhat** [comment]
> it's impossible for us to guess which specs are met in the base system or not on these distros.

Sorry if I'm blunt here, but this is such a lame excuse to not include it as a dependency.

Your app is not a part of any distro. So using this as an excuse doesn't make any sense. For all that is worth, your app is quite the opposite, it is not even tied to any platform nor with any type of device.

IF your app is using a command transitively, then you are supposed to add it as a dependency in PKGBUILD (and only used by ArchLinux).

For a regular user, these nuances are not important. They would be happy to use your app as long as it works. They simply don't care if it is written in their favorite language or is following a specification to the 't'.

Remember you are competing with the Spotify app, which despite being resource hungry does what it is supposed to do: **Play Music**.

That's all that matters, Play the damn Music! everything else is just noise.

**Comment by KRTirtho** [comment]
> IF your app is using a command transitively, then you are supposed to add it as a dependency in PKGBUILD (and only used by ArchLinux).

In that sense, Spotube also needs gtk, glib, libwayland-egl/libx11, libwayland-client, libdbus etc. etc.
But does anyone specify them as AUR dependency? No, because it is expected to be installed as part of a standard desktop

Arch is not for regular users. The users are powerusers & they build their own flavored distro

Does Arch based distros like EndeavourOS, Artix etc has this issue? No, because these were build correctly implementing all standards for a regular user centric distro

> Sorry if I'm blunt here, but this is such a lame excuse to not include it as a dependency.

Look, I'm the developer & I try to make sure my app is running on as many platform as possible. If it's not running because of my error, ok I'll fix it. But I'm not supposed to handle user errors. Sure I can assist them but I'm not responsible for these errors nor my project
Sorry to say but it's an open source hobby project, not an tech help center
