### ISSUE TITLE
Can't play full song

### ISSUE THREAD

**Issue by newtoblender** [KRTirtho/spotube#55]
**Describe the bug**
I'm unable to play the full song only a portion of it.

**To Reproduce**
1. Search for Sunny You by Kaori Ishihara
2. Click on track https://open.spotify.com/track/0FyU6kEfsxmlMpAbGzttE3
3. See runtime of 1:30 instead of 3:58
4. Add to like and try again
5. Same issue

**Expected behavior**
Track to play in full instead of a small portion.

**Screenshots**
![Screenshot_20220405-130537_Spotube](https://user-images.githubusercontent.com/101545518/161671028-c2320560-8ffa-4b6e-abb2-c0496a67094a.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - OS: Android 11 via MicroG4LineageOS 18.1
 - Version 2.0.0

**Additional context**
N/A

**Comment by KRTirtho** [comment]
Even though Spotube uses Spotify's APIs to get metadata/track/playlist/album information, it uses YouTube's APIs to fetch the actual track/song. If a track is available in Spotify but not in YouTube, this process won't work. Since *Sunny You by Kaori Ishihara*'s full version isn't available in [youtube](https://www.youtube.com/results?search_query=Sunny+You+-+Kaori+Ishihara), Spotube can't play the complete song

_It's not a bug, it's a limitation_ though you can upload the song unofficially to YouTube with proper title & Spotube might be able pick it up as the default track

**Comment by newtoblender** [comment]
Thanks for the quick reply.
