### ISSUE TITLE
YouTube Playlist Import

### ISSUE THREAD

**Issue by Xandorion** [KRTirtho/spotube#633]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

I like to use Spotube, however I still have some playlists in YouTube, I am aware that there are PlayList converters, but not every song from YouTube is available on Spotify. And as far as I know, you can only get Spotify playlists in Spotube.

### Suggested solution

I use "InnerTune" to open public YT playlist links in this app, then I can create a playlist from it in the app.

Would such a feature also be possible for Spotube? That is, to "open" or search YouTube playlists directly there. 

Unfortunately, I don't know anything about programming, so I thought that because Spotube accesses YouTube, it might be possible.

### Useful resources

https://github.com/z-huang/InnerTune

Maybe this Project could help with this.

**Comment by KRTirtho** [comment]
Unfortunately, this is not in our vision of the project currently. Spotube only syncs Spotify playlists, since it's a Spotify client.

> I am aware that there are PlayList converters, but not every song from YouTube is available on Spotify

Adding this feature in Spotube won't help either. Because Spotube also uses YouTube (piped/jiosaavn) to match the Spotify tracks, so the result will somewhat similar, if not worse.
If we need to add YouTube music library support, that involves logging in with a Google account. And do everything YouTube music does.
