### ISSUE TITLE
Android: API down error or stuck on querying 

### ISSUE THREAD

**Issue by BIZKIT551** [KRTirtho/spotube#674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to download music I get an API down error. I change to to another piped server and same error persists after restarting the app. On some servers I don't get an error, but instead the song is stuck on querying in the downloads section.

### Expected Behavior

Song should download flawlessly.

### Steps to reproduce

1. Open the app on Android.
2. Pick a song to download.
3. Be greeted with API down error or querying.

### Operating System

Android 13

### Spotube version

3.1.1

### Installation source

GitHub Releases (Binary)

**Comment by KRTirtho** [comment]
Recently, many of the Piped server stopped working due to YouTube API changes. So Spotube now defaults to official YouTube API (You can change "Settings" > "API Type")
If you want Piped to work, please open this issue on Piped repository as it's clear Piped is broken. Spotube doesn't own any Piped server nor has the ability to fix the issue 😅

**Comment by KRTirtho** [comment]
I'm closing this issue as we can't do anything about it
