### ISSUE TITLE
Nothing accessible when using a VPN 

### ISSUE THREAD

**Issue by nosteponsnakey** [KRTirtho/spotube#706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Does not remember log in state when using VPN. After PC restart, app shows as logged in (in settings screen), yet nothing is accessible.

### Expected Behavior

Remember log in state.

### Steps to reproduce

1. Start pc and VPN app
2. Open Spotube and log in with sp_key and sp_ as instructed
3. Close app
4. Restart PC
5. Open app

### Operating System

Windows 10, 22H2

### Spotube version

3.1.1

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

### Additional information

 If this is not possible to fix due to the VPN causing trouble, please just disregard my stupid report and close this.

Thanks

**Comment by MerkomassDev** [comment]
That's probably an issue on your end, i use a VPN (OpenVPN hosted on OracleCloud) daily and I don't have such issues

**Comment by MerkomassDev** [comment]
There's also a possibility that Spotify reset your password due to "suspicious activity". Check your email for a similar message
<img width="1029" alt="Screenshot_65" src="https://github.com/KRTirtho/spotube/assets/70111455/f8899d87-8eeb-45c5-a439-d1bb9aec11b9">

**Comment by KRTirtho** [comment]
I've also tested on multiple platforms (Windows, Linux, Android) with multiple VPNs (Express, Nord) & Tor (Orbit for Android) as well but it worked perfectly fine on every single test

**Comment by KRTirtho** [comment]
@callegar Does [these](https://pub.dev/packages/internet_connection_checker#default_addresses) dns resolvers work in you environment?
Spotube uses these to detect offline connection

**Comment by KRTirtho** [comment]
Make sure these DNS resolvers addresses works when using the VPN/proxy/firewall-config

| Address        | Provider   | Info                                              |
| :------------- | :--------- | :------------------------------------------------ |
| 1.1.1.1        | CloudFlare | <https://1.1.1.1>                                 |
| 1.0.0.1        | CloudFlare | <https://1.1.1.1>                                 |
| 8.8.8.8        | Google     | <https://developers.google.com/speed/public-dns/> |
| 8.8.4.4        | Google     | <https://developers.google.com/speed/public-dns/> |
| 208.67.222.222 | OpenDNS    | <https://use.opendns.com/>                        |
| 208.67.220.220 | OpenDNS    | <https://use.opendns.com/>                        |


Or you can turn off DNS filtering if it's turned on according to this https://github.com/RounakTadvi/internet_connection_checker/issues/9

**Comment by callegar** [comment]
I suppose it is this. Looks like on this network I can only use the DNS assigned by DHCP and no other. Wonder if spotube could include a configuration option about how to detect offline connection (e.g., merely pinging 8.8.8.8) would work.

**Comment by ArchangeGabriel** [comment]
> Does [these](https://pub.dev/packages/internet_connection_checker#default_addresses) dns resolvers work in you environment? Spotube uses these to detect offline connection

I’ve noticed indeed that Spotube (on Android) is making requests to these DNS resolver constantly (I would say roughly every second but did not measure), which is increasing the battery consumption a lot because this is happening even if there is nothing playing currently, so that my phone cannot go to sleep. So combined with being unable to work under some not-so-rare circumstances, this does not seems to be a good method for checking whether network is available…

In the case of Android, I’m pretty sure there is an API available for this (a 30s random search gave me https://stackoverflow.com/questions/65238297/android-how-to-check-internet-connectivity-on-api-level-29-or-higher-in-android).

At the very least I think you should not check constantly, but e.g. only when you fail to access what you actually want to access? And only then produce a “toast” notification, which can be more helpful (you could say either whether there does not seem to be any network connectivity or whether there is one but you cannot access content — maybe this is actually implemented, but ). This would solve most issues reported here, since if everything works people using blocking VPN would not be affected by unneeded checks. ;)

**Comment by KRTirtho** [comment]
@ArchangeGabriel here, we're not trying to know if your device Wi-Fi/data is open or not. We're trying to determine whether the device has internet connection (the device can connect + transfer data) 

> I’ve noticed indeed that Spotube (on Android) is making requests to these DNS resolver constantly (I would say roughly every second but did not measure), which is increasing the battery consumption a lot because this is happening even if there is nothing playing currently, so that my phone cannot go to sleep

The requests are made in the background, and it's roughly every 5 minutes. Also, these are not HTTP requests. Just IP lookup, which are very inexpensive and in theory shouldn't drain your battery. Also, your screen not going dim is nothing to do with Spotube. It's probably your sleep timer
The problem is with VPN/Proxy connection. And the package used under the hood uses cloudflare or google DNS which are often gets overridden by VPNs. So basically the fix is using `google.com` (or `baidu.com` for China) 

> So combined with being unable to work under some not-so-rare circumstances, this does not seems to be a good method for checking whether network is available…

I'm not sure what you're trying to say but this exactly how apps detect offline/network strength

> In the case of Android, I’m pretty sure there is an API available for this (a 30s random search gave me https://stackoverflow.com/questions/65238297/android-how-to-check-internet-connectivity-on-api-level-29-or-higher-in-android).

We've a plugin connectivity_plus which uses this very API and this Android API can only detect whether the device has network connection or not. It can't detect if the device have actual internet connection

> a 30s random search gave me 

Are u challenging me on a who can search fast competition lol :joy:

**Comment by callegar** [comment]
May I suggest offering also alternate methods to verify whether internet connection is available? This would be important because in many situations (institutional accounts, VPN, ISPs) you may find access to external DNS servers blocked.

One possibility would be to query the system DNS for a host and checking that the DNS returns the *right* answer.

Yet another possibility and my suggestion is to offer the option to verify connectivity via HTTP. This could be done taking advantage of the mozilla captive portal detector. Connecting to http://detectportal.firefox.com should deliver the string "success" if you have connectivity.

One may want to put the "check connectivity method" (DNS/HTTP) under an option. Even better would be to switch between the two: e.g. try DNS, if that fails switch to HTTP; or try HTTP, if that fails switch to DNS.

**Comment by KRTirtho** [comment]
@callegar
> One possibility would be to query the system DNS for a host and checking that the DNS returns the right answer.

This is what `InternetAddress.lookup` does and even that is having issues because we're querying for domain names for IP such as 8.8.8.8 which are easily blocked by some ISP (which is not legal in some areas) thus now we're using the domain (google.com or baidu.com for China) to get the IP which in theory should work better

> Yet another possibility and my suggestion is to offer the option to verify connectivity via HTTP. This could be done taking advantage of the mozilla captive portal detector. Connecting to http://detectportal.firefox.com/ should deliver the string "success" if you have connectivity.
> One may want to put the "check connectivity method" (DNS/HTTP) under an option. Even better would be to switch between the two: e.g. try DNS, if that fails switch to HTTP; or try HTTP, if that fails switch to DNS.


Yes I did something similar but with a HTTP HEAD request to google.com or (baidu.com for China) which tends to be faster

**Comment by KRTirtho** [comment]
Everything is updated in Nightly so please check if it works or not

**Comment by callegar** [comment]
Nightly is fine. Thanks!!! Can you be so kind to push this also to the flatpak soon?

**Comment by KRTirtho** [comment]
Yea I am planning a release today

**Comment by callegar** [comment]
Was mentioning that because I have actually recedived a flatpak update for the package right today, but it is still at 3.1.2 and still failing in my network environment... so another one is coming?

**Comment by KRTirtho** [comment]
Yea

**Comment by fxzxmicah** [comment]
No, it hasn't been fixed. The play button is still spinning wildly and never stops.

**Comment by KRTirtho** [comment]
Did you update to 3.2.0?

**Comment by fxzxmicah** [comment]
> Did you update to 3.2.0?

Of course.

**Comment by fxzxmicah** [comment]
![Screenshot_20231116_102213](https://github.com/KRTirtho/spotube/assets/48860358/27180341-df69-492c-9970-5aca1a258fc4)
In the web request log I can see that the app is constantly making requests to YouTube.

**Comment by KRTirtho** [comment]
Yes, it's supposed to make requests to YouTube for the Audio. Is YouTube accessible in your region?

**Comment by fxzxmicah** [comment]
> Is YouTube accessible in your region?

Directly, no, but yes with a VPN (or something like that).

**Comment by fxzxmicah** [comment]
After I turned off and then turned on the option to block sponsors, I restarted the application again and it seems to have returned to normal for now.
Network requests also seem to have returned to normal. It turns out that crazily making requests looks like launching a ddos attack on www.youtube.com. Now it only requests www.youtube.com a few times and then makes some requests to googlevideo.com instead.

**Comment by KRTirtho** [comment]
Ok, change "Settings" > "API Type" to "Piped" and "Settings" > "Piped Server Instance" to "drgns.space"

**Comment by fxzxmicah** [comment]
> Ok, change "Settings" > "API Type" to "Piped" and "Settings" > "Piped Server Instance" to "drgns.space"

I tried several times but it didn't work.

**Comment by KRTirtho** [comment]
You can try the nightly version, which includes the new JioSaavn based Audio API. And as far as I know, JioSaavn is available in China too

**Comment by KRTirtho** [comment]
I'm planning to implement the Kuwo following [feeluown-kuwo](https://github.com/feeluown/feeluown-kuwo) for the Chinese users. If anyone want to help, we're open to it

**Comment by fxzxmicah** [comment]
I don't know why it's not working. I can use YouTube with my vpn on, but I can't use spotube at the same time (mostly).

**Comment by ArchangeGabriel** [comment]
> @ArchangeGabriel here, we're not trying to know if your device Wi-Fi/data is open or not. We're trying to determine whether the device has internet connection (the device can connect + transfer data)
> 
> > I’ve noticed indeed that Spotube (on Android) is making requests to these DNS resolver constantly (I would say roughly every second but did not measure), which is increasing the battery consumption a lot because this is happening even if there is nothing playing currently, so that my phone cannot go to sleep
> 
> The requests are made in the background, and it's roughly every 5 minutes. Also, these are not HTTP requests. Just IP lookup, which are very inexpensive and in theory shouldn't drain your battery. Also, your screen not going dim is nothing to do with Spotube. It's probably your sleep timer The problem is with VPN/Proxy connection. And the package used under the hood uses cloudflare or google DNS which are often gets overridden by VPNs. So basically the fix is using `google.com` (or `baidu.com` for China)

My screen was going off, that’s not what I meant by not going to sleep. I’m using a tool to measure the time spent screen on/off and in sleep/deep sleep. With the previous release of Spotube making network request every second (actually looked at the firewall log this time), it could not go to deep sleep nor sleep. Now it does. :)

> > So combined with being unable to work under some not-so-rare circumstances, this does not seems to be a good method for checking whether network is available…
> 
> I'm not sure what you're trying to say but this exactly how apps detect offline/network strength
> 
> > In the case of Android, I’m pretty sure there is an API available for this (a 30s random search gave me https://stackoverflow.com/questions/65238297/android-how-to-check-internet-connectivity-on-api-level-29-or-higher-in-android).
> 
> We've a plugin connectivity_plus which uses this very API and this Android API can only detect whether the device has network connection or not. It can't detect if the device have actual internet connection

OK I see the difference here. But as I said before, you should only try to check that if you can’t access otherwise, not constantly.

Anyway, with the release of Spotube that went out with the changes closing this issue, everything is working perfectly fine now (well, except that for some reason the app is now displayed as “App Killer Manager”, but I don’t really mind ^^), so for me that’s all there is to know. ;) Thanks for your work on this project !

**Comment by fxzxmicah** [comment]
I don't know what went wrong. I can actually use JioSaavn without using a VPN. But after switching to JioSaavn API in the application, even if I turn off the VPN, the application is still unusable, just like any other APIs.
