### ISSUE TITLE
Show m3u playlists

### ISSUE THREAD

**Issue by GrafKiedyOdcinek** [KRTirtho/spotube#729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

There is no option to have offline playlists.

### Suggested solution

Please support m3u playlists, because it will allow playlists without signing in to Spotify. So it's through the app instead of an account like what other Foss music apps have. It would be helpful.

**Comment by KRTirtho** [comment]
Sorry but I don't think it really makes sense to include this feature in an Spotify Client app. Because it was designed to for spotify integration & not that much of an offline player

Although local/downloaded track playlists are planned to be supported but I don't see any way to support m3u playlists

If you want m3u functionality, you can consider the alternatives like VLC or mpv
