### ISSUE TITLE
Show market place (recommendation country) in full name instead of abbreviation

### ISSUE THREAD

**Issue by momobobe** [KRTirtho/spotube#96]
The two-letter code for country is confusing in most cases if it's not known in advance. Please use full names (commonly used ones, no intention to bother asking for official names) for better readability.

**Comment by KRTirtho** [comment]
Showing small country code is more efficient & at the same time takes less space. And it's a standard thing to use abbreviation instead of full country names around the world. But there's no rule for following those standards so there's always room for improvement. Since you're interested in full country names you can contribute to the project by writing the names

Country Codes are available at https://github.com/KRTirtho/spotube/blob/master/lib/models/SpotifyMarkets.dart You can just change those to appropriate country names & create a PR
